name: CustomEnchant
main: me.jtghawk137.ce.CustomEnchant
author: JTGhawk137
description: Plugin for custom enchantments in Minecraft
version: 1.0.0
commands:
    ce:
        description: Custom enchants command
        usage: /<command>
        Permission: nsp.headadmin